### ISSUE TITLE
Borde förtydliga vad som ska blandas ihop. (Fattiga riddare)

### ISSUE THREAD

**Issue by Alexander-Hjelm** [medik/Mat#4]
Som det står nu i filen 'Fattiga-riddare.md' kommer jag tro att jag ska blanda ner bröd och parmesan i röran.

**Comment by medik** [comment]
Ska fixa.

**Comment by medik** [comment]
Löser #5 din bugg?

**Comment by Alexander-Hjelm** [comment]
Nej allså, förstår jag rätt sp ska jag blanda ägg, mjäl och mjölk i en bunke. Detta borde kanske framgå i första meningen, för "blanda helvetet" tolkar jag som blanda allting.

**Comment by medik** [comment]
Skrivit nu smethelvetet och definerat vad som är smet och inte. Se #5. Om allt är ok mergar jag det till master.

**Comment by Alexander-Hjelm** [comment]
Jaha brödet ska faktiskt vara med i smeten? Ok, men merga på!

**Comment by medik** [comment]
Brödet (som helst ska vara torrt och gammalt) ska ta upp smeten. Men visst, det kanske inte ska vara under rubriken "Smet".... Fixar det.
